services:
  fast-api:
    container_name: backend
    build:
      context: ./backend
      dockerfile: DockerFile
    environment:
      - QUEUE_HOST=rabbitMQ
    command: python backend.py
    ports:
      - 8888:8888
    networks:
      - my-network
    volumes:
      - ./backend:/app
    depends_on:
      - rabbitMQ

  discord:
    container_name: discord
    build:
      context: ./discord
      dockerfile: DockerFile
    environment:
      - QUEUE_HOST=rabbitMQ
      - DISCORD_TOKEN= Discrod Bot Token
      - CHANNEL_ID= Discord Channel ID
    command: python launch.py
    networks:
      - my-network
    volumes:
      - ./discord:/app
    depends_on:
      - rabbitMQ

  rabbitMQ:
    container_name: rabbitMQ
    image: hub.hamdocker.ir/rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    # environment:
    #   - RABBITMQ_DEFAULT_USER=guest
    #   - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - my-network


networks:
  my-network:
    driver: bridge